// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	// Тип токена для заголовка Authorization, всегда "Bearer".
	TokenType string `json:"tokenType"`
	// Срок жизни accessToken в секундах.
	ExpiresIn int `json:"expiresIn"`
}

// Бюджет — это план расходов по категориям, а не процент от дохода: он не
// требует и не зависит от указания планового дохода. income здесь — только
// справочная величина, посчитанная из фактических INCOME-транзакций за
// период; по факту дохода за период она равна summary.income.total.
type Budget struct {
	// Суммарный фактический доход группы за период (справочно, не влияет на план расходов).
	Income *Money `json:"income"`
	// Разбивка расходов по категориям с лимитами.
	Categories []*BudgetCategory `json:"categories"`
	// Сумма, уже распределённая по категориям.
	TotalAllocated *Money `json:"totalAllocated"`
	// Доход за вычетом totalAllocated; может быть отрицательным.
	Free *Money `json:"free"`
}

type BudgetCategory struct {
	CategoryID uuid.UUID `json:"categoryId"`
	// Сумма, выделенная на категорию за период (равна её monthlyLimit).
	Amount *Money `json:"amount"`
}

type Category struct {
	ID uuid.UUID `json:"id"`
	// Иконка категории (эмодзи).
	Icon string `json:"icon"`
	Name string `json:"name"`
	// Месячный лимит расходов по категории; null — лимит не задан.
	MonthlyLimit *Money `json:"monthlyLimit,omitempty"`
}

type CategoryAmount struct {
	CategoryID uuid.UUID `json:"categoryId"`
	Amount     *Money    `json:"amount"`
}

type ContributeGoalInput struct {
	Amount *MoneyInput `json:"amount"`
	Date   *time.Time  `json:"date,omitempty"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
	// Иконка категории (эмодзи).
	Icon         string      `json:"icon"`
	MonthlyLimit *MoneyInput `json:"monthlyLimit,omitempty"`
}

// Для type = PERSONAL владельцем становится вызывающий пользователь.
type CreateGoalInput struct {
	Name         string      `json:"name"`
	Icon         *string     `json:"icon,omitempty"`
	TargetAmount *MoneyInput `json:"targetAmount"`
	Type         GoalType    `json:"type"`
}

type CreateGroupInput struct {
	Name string `json:"name"`
}

type CreateTransactionInput struct {
	Type   TransactionType `json:"type"`
	Amount *MoneyInput     `json:"amount"`
	// Обязателен для type = EXPENSE; должен отсутствовать для type = INCOME.
	CategoryID *uuid.UUID  `json:"categoryId,omitempty"`
	Payer      *PayerInput `json:"payer"`
	Date       time.Time   `json:"date"`
	Comment    *string     `json:"comment,omitempty"`
}

type ExpenseSummary struct {
	// Суммарный расход группы за период.
	Total *Money `json:"total"`
	// Разбивка расхода по категориям.
	ByCategory []*CategoryAmount `json:"byCategory"`
	// Разбивка расхода по участникам (учитывает доли в разделённых операциях).
	ByMember []*MemberAmount `json:"byMember"`
}

type Goal struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Icon          *string    `json:"icon,omitempty"`
	TargetAmount  *Money     `json:"targetAmount"`
	CurrentAmount *Money     `json:"currentAmount"`
	Type          GoalType   `json:"type"`
	OwnerUserID   *uuid.UUID `json:"ownerUserId,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
}

// Один взнос в цель накопления.
type GoalContribution struct {
	ID     uuid.UUID `json:"id"`
	GoalID uuid.UUID `json:"goalId"`
	Amount *Money    `json:"amount"`
	Date   time.Time `json:"date"`
}

type Group struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// Полный список участников группы.
	Members []*GroupMember `json:"members"`
}

type GroupMember struct {
	User *User `json:"user"`
	// ⚠️ зависит от решения о ролевой модели внутри группы.
	Role *GroupRole `json:"role,omitempty"`
}

type GroupSummary struct {
	// Текущий баланс группы (доходы минус расходы) на момент запроса.
	Balance *Money `json:"balance"`
	// Изменение баланса за запрошенный период (period), может быть отрицательным.
	BalanceDeltaMonth *Money          `json:"balanceDeltaMonth"`
	Income            *IncomeSummary  `json:"income"`
	Expense           *ExpenseSummary `json:"expense"`
}

// Элемент списка групп текущего пользователя (без полного списка участников).
type GroupSummaryItem struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	MembersCount int       `json:"membersCount"`
}

type IncomeSummary struct {
	// Суммарный доход группы за период.
	Total *Money `json:"total"`
	// Разбивка дохода по участникам.
	ByMember []*MemberAmount `json:"byMember"`
}

// ⚠️ зависит от решения: добавление по username, либо по email с генерацией инвайт-кода.
type InviteMemberInput struct {
	Username *string `json:"username,omitempty"`
	Email    *string `json:"email,omitempty"`
}

// Заполняется одно из полей, в зависимости от способа приглашения (⚠️ см. InviteMemberInput).
type InviteResult struct {
	// Идентификатор инвайта, если приглашение шло по email-коду.
	InviteID *uuid.UUID `json:"inviteId,omitempty"`
	// Идентификатор нового участника, если приглашение шло по username (добавление сразу).
	MemberID *uuid.UUID `json:"memberId,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MemberAmount struct {
	UserID uuid.UUID `json:"userId"`
	Amount *Money    `json:"amount"`
}

type Money struct {
	// Сумма в минимальных единицах валюты (копейках).
	Amount int `json:"amount"`
}

type MoneyInput struct {
	// Сумма в минимальных единицах валюты (копейках).
	Amount int `json:"amount"`
}

type Mutation struct {
}

type Payer struct {
	Mode PayerMode `json:"mode"`
	// Плательщик, если mode = USER; null, если mode = SPLIT.
	UserID *uuid.UUID `json:"userId,omitempty"`
	// Явные суммы участников, если mode = SPLIT; null, если mode = USER. Сумма amount по всем элементам равна Transaction.amount.
	Shares []*PayerShare `json:"shares,omitempty"`
}

type PayerInput struct {
	Mode PayerMode `json:"mode"`
	// Обязателен, если mode = USER.
	UserID *uuid.UUID `json:"userId,omitempty"`
	// Суммы участников, если mode = SPLIT; не обязателен — если не задан, сумма делится поровну между всеми участниками группы. Сумма amount по всем элементам должна быть равна Transaction.amount.
	Shares []*PayerShareInput `json:"shares,omitempty"`
}

// Доля одного участника при payer.mode = SPLIT.
type PayerShare struct {
	UserID uuid.UUID `json:"userId"`
	Amount *Money    `json:"amount"`
}

type PayerShareInput struct {
	UserID uuid.UUID   `json:"userId"`
	Amount *MoneyInput `json:"amount"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Transaction struct {
	ID     uuid.UUID       `json:"id"`
	Type   TransactionType `json:"type"`
	Amount *Money          `json:"amount"`
	// Категория расхода; null для type = INCOME — доходы категорий не имеют.
	Category *Category `json:"category,omitempty"`
	Payer    *Payer    `json:"payer"`
	Date     time.Time `json:"date"`
	Comment  *string   `json:"comment,omitempty"`
	// Пользователь, создавший операцию (может отличаться от payer).
	CreatedBy uuid.UUID `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

type TransactionFilter struct {
	Type        *TransactionType `json:"type,omitempty"`
	CategoryID  *uuid.UUID       `json:"categoryId,omitempty"`
	PayerUserID *uuid.UUID       `json:"payerUserId,omitempty"`
	// Нижняя граница по date, включительно.
	DateFrom *time.Time `json:"dateFrom,omitempty"`
	// Верхняя граница по date, включительно.
	DateTo *time.Time `json:"dateTo,omitempty"`
}

type TransactionList struct {
	Items []*Transaction `json:"items"`
	// Курсор для запроса следующей страницы через аргумент after; null, если дальше ничего нет.
	NextCursor *string `json:"nextCursor,omitempty"`
	// true, если есть ещё операции после текущей страницы.
	HasMore bool `json:"hasMore"`
	// Общее число операций, подходящих под filter, вне зависимости от размера текущей страницы.
	Total int `json:"total"`
}

type UpdateCategoryInput struct {
	Name         *string     `json:"name,omitempty"`
	Icon         *string     `json:"icon,omitempty"`
	MonthlyLimit *MoneyInput `json:"monthlyLimit,omitempty"`
}

type UpdateGoalInput struct {
	Name         *string     `json:"name,omitempty"`
	Icon         *string     `json:"icon,omitempty"`
	TargetAmount *MoneyInput `json:"targetAmount,omitempty"`
}

type UpdateGroupInput struct {
	Name string `json:"name"`
}

type UpdateTransactionInput struct {
	Type       *TransactionType `json:"type,omitempty"`
	Amount     *MoneyInput      `json:"amount,omitempty"`
	CategoryID *uuid.UUID       `json:"categoryId,omitempty"`
	Payer      *PayerInput      `json:"payer,omitempty"`
	Date       *time.Time       `json:"date,omitempty"`
	Comment    *string          `json:"comment,omitempty"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

type WithdrawFromGoalInput struct {
	Amount *MoneyInput `json:"amount"`
	Date   *time.Time  `json:"date,omitempty"`
}

type GoalType string

const (
	// Взносы от нескольких участников группы, поровну.
	GoalTypeShared GoalType = "SHARED"
	// Взносы только от одного участника (ownerUserId).
	GoalTypePersonal GoalType = "PERSONAL"
)

var AllGoalType = []GoalType{
	GoalTypeShared,
	GoalTypePersonal,
}

func (e GoalType) IsValid() bool {
	switch e {
	case GoalTypeShared, GoalTypePersonal:
		return true
	}
	return false
}

func (e GoalType) String() string {
	return string(e)
}

func (e *GoalType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GoalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GoalType", str)
	}
	return nil
}

func (e GoalType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GoalType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GoalType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GroupRole string

const (
	GroupRoleOwner  GroupRole = "OWNER"
	GroupRoleMember GroupRole = "MEMBER"
)

var AllGroupRole = []GroupRole{
	GroupRoleOwner,
	GroupRoleMember,
}

func (e GroupRole) IsValid() bool {
	switch e {
	case GroupRoleOwner, GroupRoleMember:
		return true
	}
	return false
}

func (e GroupRole) String() string {
	return string(e)
}

func (e *GroupRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GroupRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GroupRole", str)
	}
	return nil
}

func (e GroupRole) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GroupRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GroupRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HealthStatus string

const (
	HealthStatusOk   HealthStatus = "OK"
	HealthStatusDown HealthStatus = "DOWN"
)

var AllHealthStatus = []HealthStatus{
	HealthStatusOk,
	HealthStatusDown,
}

func (e HealthStatus) IsValid() bool {
	switch e {
	case HealthStatusOk, HealthStatusDown:
		return true
	}
	return false
}

func (e HealthStatus) String() string {
	return string(e)
}

func (e *HealthStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HealthStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HealthStatus", str)
	}
	return nil
}

func (e HealthStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HealthStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HealthStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PayerMode string

const (
	PayerModeUser PayerMode = "USER"
	// Сумма делится между несколькими участниками группы; см. Payer.shares.
	PayerModeSplit PayerMode = "SPLIT"
)

var AllPayerMode = []PayerMode{
	PayerModeUser,
	PayerModeSplit,
}

func (e PayerMode) IsValid() bool {
	switch e {
	case PayerModeUser, PayerModeSplit:
		return true
	}
	return false
}

func (e PayerMode) String() string {
	return string(e)
}

func (e *PayerMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayerMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayerMode", str)
	}
	return nil
}

func (e PayerMode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PayerMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PayerMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionType string

const (
	TransactionTypeIncome  TransactionType = "INCOME"
	TransactionTypeExpense TransactionType = "EXPENSE"
)

var AllTransactionType = []TransactionType{
	TransactionTypeIncome,
	TransactionTypeExpense,
}

func (e TransactionType) IsValid() bool {
	switch e {
	case TransactionTypeIncome, TransactionTypeExpense:
		return true
	}
	return false
}

func (e TransactionType) String() string {
	return string(e)
}

func (e *TransactionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionType", str)
	}
	return nil
}

func (e TransactionType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
