package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"OurKoshelechek/graph/model"
	"context"

	"github.com/google/uuid"
)

// UpdateBudgetSplit is the resolver for the updateBudgetSplit field.
func (r *mutationResolver) UpdateBudgetSplit(ctx context.Context, groupID uuid.UUID, split []*model.BudgetSplitInput) ([]*model.BudgetSplit, error) {
	return r.BudgetService.UpdateSplit(ctx, groupID, split)
}

// Budget is the resolver for the budget field.
func (r *queryResolver) Budget(ctx context.Context, groupID uuid.UUID, period string) (*model.Budget, error) {
	return r.BudgetService.Budget(ctx, groupID, period)
}
