package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"OurKoshelechek/graph/model"
	"context"

	"github.com/google/uuid"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, groupID uuid.UUID, input model.CreateCategoryInput) (*model.Category, error) {
	return r.CategoryService.Create(ctx, groupID, input)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, groupID uuid.UUID, categoryID uuid.UUID, input model.UpdateCategoryInput) (*model.Category, error) {
	return r.CategoryService.Update(ctx, groupID, categoryID, input)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, groupID uuid.UUID, categoryID uuid.UUID) (bool, error) {
	return r.CategoryService.Delete(ctx, groupID, categoryID)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, groupID uuid.UUID) ([]*model.Category, error) {
	return r.CategoryService.List(ctx, groupID)
}
