package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/google/uuid"

	"OurKoshelechek/graph/model"
	"OurKoshelechek/internal/platform"
)

// CreateGoal is the resolver for the createGoal field.
func (r *mutationResolver) CreateGoal(ctx context.Context, groupID uuid.UUID, input model.CreateGoalInput) (*model.Goal, error) {
	return r.GoalService.Create(ctx, groupID, input)
}

// UpdateGoal is the resolver for the updateGoal field.
func (r *mutationResolver) UpdateGoal(ctx context.Context, groupID uuid.UUID, goalID uuid.UUID, input model.UpdateGoalInput) (*model.Goal, error) {
	return r.GoalService.Update(ctx, groupID, goalID, input)
}

// DeleteGoal is the resolver for the deleteGoal field.
func (r *mutationResolver) DeleteGoal(ctx context.Context, groupID uuid.UUID, goalID uuid.UUID) (bool, error) {
	return r.GoalService.Delete(ctx, groupID, goalID)
}

// ContributeToGoal is the resolver for the contributeToGoal field.
func (r *mutationResolver) ContributeToGoal(ctx context.Context, groupID uuid.UUID, goalID uuid.UUID, input model.ContributeGoalInput) (*model.GoalContribution, error) {
	createdBy, err := platform.CurrentUserID(ctx)
	if err != nil {
		return nil, err
	}
	return r.GoalService.Contribute(ctx, groupID, goalID, createdBy, input)
}

// Goals is the resolver for the goals field.
func (r *queryResolver) Goals(ctx context.Context, groupID uuid.UUID) ([]*model.Goal, error) {
	return r.GoalService.List(ctx, groupID)
}

// GoalContributions is the resolver for the goalContributions field.
func (r *queryResolver) GoalContributions(ctx context.Context, groupID uuid.UUID, goalID uuid.UUID) ([]*model.GoalContribution, error) {
	return r.GoalService.ListContributions(ctx, groupID, goalID)
}
