package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"OurKoshelechek/graph/model"
	"context"

	"github.com/google/uuid"
)

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	return r.GroupService.Create(ctx, input)
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, groupID uuid.UUID, input model.UpdateGroupInput) (*model.Group, error) {
	return r.GroupService.Update(ctx, groupID, input)
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, groupID uuid.UUID, input model.InviteMemberInput) (*model.InviteResult, error) {
	return r.GroupService.InviteMember(ctx, groupID, input)
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	return r.GroupService.RemoveMember(ctx, groupID, userID)
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.GroupSummaryItem, error) {
	return r.GroupService.List(ctx)
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, groupID uuid.UUID) (*model.Group, error) {
	return r.GroupService.Get(ctx, groupID)
}
