package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"OurKoshelechek/graph/model"
	"context"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (model.HealthStatus, error) {
	if err := r.DB.Ping(ctx); err != nil {
		return model.HealthStatusDown, nil
	}
	return model.HealthStatusOk, nil
}
