package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/google/uuid"

	"OurKoshelechek/graph/model"
)

// Summary is the resolver for the summary field.
func (r *queryResolver) Summary(ctx context.Context, groupID uuid.UUID, period string) (*model.GroupSummary, error) {
	return r.SummaryService.Summary(ctx, groupID, period)
}
