package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/google/uuid"

	"OurKoshelechek/graph/model"
	"OurKoshelechek/internal/platform"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, groupID uuid.UUID, input model.CreateTransactionInput) (*model.Transaction, error) {
	createdBy, err := platform.CurrentUserID(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionService.Create(ctx, groupID, createdBy, input)
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, groupID uuid.UUID, transactionID uuid.UUID, input model.UpdateTransactionInput) (*model.Transaction, error) {
	return r.TransactionService.Update(ctx, groupID, transactionID, input)
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, groupID uuid.UUID, transactionID uuid.UUID) (bool, error) {
	return r.TransactionService.Delete(ctx, groupID, transactionID)
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, groupID uuid.UUID, filter *model.TransactionFilter, first *int, after *uuid.UUID) (*model.TransactionList, error) {
	return r.TransactionService.List(ctx, groupID, filter, first, after)
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, groupID uuid.UUID, transactionID uuid.UUID) (*model.Transaction, error) {
	return r.TransactionService.Get(ctx, groupID, transactionID)
}
