query Summary($groupId: UUID!, $period: String!) {
  summary(groupId: $groupId, period: $period) {
    balance {
      amount
    }
    balanceDeltaMonth {
      amount
    }
    income {
      total {
        amount
      }
      byMember {
        userId
        amount {
          amount
        }
      }
    }
    expense {
      total {
        amount
      }
      byCategory {
        categoryId
        amount {
          amount
        }
      }
      byMember {
        userId
        amount {
          amount
        }
      }
    }
  }
}

query PeriodSummary($groupId: UUID!, $dateFrom: String!, $dateTo: String!) {
  periodSummary(groupId: $groupId, dateFrom: $dateFrom, dateTo: $dateTo) {
    income {
      total {
        amount
      }
      byMember {
        userId
        amount {
          amount
        }
      }
    }
    expense {
      total {
        amount
      }
      byCategory {
        categoryId
        amount {
          amount
        }
        byMember {
          userId
          amount {
            amount
          }
        }
      }
      byMember {
        userId
        amount {
          amount
        }
      }
    }
  }
}
